### ISSUE TITLE
可以直接加在资源管理器上的文件夹后面吗

### ISSUE THREAD

**Issue by littleinsz** [Muromi-Rikka/folder-alias#3]
你好，因为新的bar操作不太方便，少了原先资源管理器内文件夹和文件的右键菜单，所以请问一下能否实现给资源管理器的文件夹或文件添加中文说明，谢谢！

**Comment by Muromi-Rikka** [comment]
@littleinsz jetbrains系列的编辑器是可以实现的，vscode目前没看到对应的api

**Comment by Muromi-Rikka** [comment]
已实现
